name: Open Sheet Live Auto Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-ssh-command:
    environment: opensheet
    runs-on: ubuntu-latest
    steps:
      - name: Install new npm and composer packages and migrate
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          script: |
            echo "Auto Deploy"
            cd htdocs/opensheet.net/
            git reset --hard
            git pull
            npm install
            composer install
            php artisan migrate
            npm run build
